config/routes.rb
Rails.application.routes.draw do
  resources :users,:posts,:comments
  root :to => 'welcome#index'

  get '/login' => "sessions#signin"
  post '/login' => "sessions#login"
  get '/logout' => "sessions#logout"
  get '/login' => "sessions#show"
  get '/donation' => "application#donation"
  get '/signup' => "users#signup"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_current_user
    redirect_to '/' unless current_user
  end

  def current_user
    User.find(session[:user_id])
  end

  def donation
    render '/donation'
  end
end

app/controllers/auth.rb
get '/' do
   erb :welcome
end

get '/login' do
  erb :login
end

post '/login' do
  user = User.authenticate(params[:name], params[:password])
  if user
    session[:user_id] = user.id
    redirect '/posts'
  else
    redirect '/login'
  end
end

get '/donation' do
  erb :donation
end

get '/signup' do
  erb :signup
end

post '/signup' do
  if params[:password] == params[:password_confirmation]
    new_user = User.create(name: params[:name], password: params[:password], password_confirmation: params[:password_confirmation])
    session[:user_id] = new_user.id
    redirect '/index'
  else
    redirect '/signup'
  end
end

get '/logout' do
  session.delete(:user_id)
  redirect '/'
end

app/controllers/comments.rb
get '/comments' do
  @comments = Comment.all
  erb :comments
end

post '/posts/:id/comment/new' do
  new_comment = current_user.comments.create(text: params[:comment], post_id: params[:id])
  redirect "/posts/#{params[:id]}"
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/concerns/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'welcome'
  end

end

app/controllers/posts.rb
get '/index' do
  @posts = Post.all
  erb :posts
end

get '/posts' do
  @posts = Post.all
  erb :posts
end

get '/posts/new' do
  erb :new_post
end

get '/posts/:id/edit' do |id|
  @post = Post.find(id)
  erb :update, layout: false
end

get '/posts/:id' do
  @post = Post.find(params[:id])
  erb :post
end

post '/posts' do
  @user = current_user
  @post = @user.posts.create(title: params[:title], content: params[:content])
  redirect "/posts/#{@post.id}"
end

delete '/posts/:id' do |id|
  Post.destroy(id)
end

put '/posts/:id' do
  id = params[:id]
  @post = Post.find(id)
  @post.update(id: id, user_id: current_user.id, title: params[:title], content: params[:content])
 redirect "/posts"
end

post '/post/new' do
  @post = Post.create(title: params[:title], content: params[:content])
  redirect "/posts"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def create
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def signin

  end

  def login
    p "*"*30
    p params
    p "*"*30
     user = User.authenticate(session_params)
    if user
      session[:user_id] = user.id
      redirect '/posts'
    else
      redirect '/login'
    end
  end

  def logout
    session.clear
  end

  private

  def session_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

end

app/controllers/users.rb
get '/profiles/:id' do
  @user=User.find(params[:id])
  erb :profile
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def signup
    if params[:password] == params[:password_confirmation]
    @new_user = User.create(name: params[:name], password: params[:password], password_confirmation: params[:password_confirmation])
    session[:user_id] = @new_user.id
    redirect_to @new_user
    else
    redirect '/signup'
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'welcome'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth.rb
def current_user
  if session[:user_id]
    return User.find(session[:user_id])
  else
    return nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clubhouse</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
User index

app/views/users/signup.html.erb
<div id=signtop>
  <h1> Hi!</h1>
  </div>
<form action='/signup' method='POST'>
  <input type="text" name="name" placeholder="Your Username Here!">
  <input type="password" name="password" placeholder="Your Password Here!">
  <input type="password" name="password_confirmation" placeholder="Confirm Your Password!">
  <input type="submit">
</form>

app/views/welcome/welcome.html.erb
  <div id='wrap'>
  <p><img id='center' src="/img/doge.png" width=200px; ></p>
  <h1 id='w_h1'>Welcome to the Club House for <br>Phase Repeaters</h1>
  <br>
  <p><a href="/donation"> Donation is here!  </a></p>
 <h3>Repeating is not a shame,but tiring. Cheer up!</h3>
<br>
<br>

    <!-- <p><a href="/signup">Don't have an account?  Sign Up here!</a><p> -->
      <%= link_to("Don't have an account?  Sign Up here!", login_path) %>
  </div>
  <hr>
  <footer>
    <p> Dongchul Lee, DVC squirrel 2015. All rights reserved </p>
  </footer>